// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversations,
    messages,
    sessionUsers,
    outboxEntries,
    syncStates,
    processedEvents,
  ];
  late final Shape0 conversations = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messages = Shape1(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_1,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_17,
        _column_18,
        _column_32,
        _column_33,
        _column_34,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessionUsers = Shape2(
    source: i0.VersionedTable(
      entityName: 'session_users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 outboxEntries = Shape3(
    source: i0.VersionedTable(
      entityName: 'outbox_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_17,
        _column_45,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 syncStates = Shape4(
    source: i0.VersionedTable(
      entityName: 'sync_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scope)'],
      columns: [
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 processedEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'processed_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(event_id)'],
      columns: [_column_58, _column_59, _column_60],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get channelId =>
      columnsByName['channel_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerId =>
      columnsByName['customer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assigneeId =>
      columnsByName['assignee_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerName =>
      columnsByName['customer_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerAvatarUrl =>
      columnsByName['customer_avatar_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subject =>
      columnsByName['subject']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get unreadCount =>
      columnsByName['unread_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isBotEnabled =>
      columnsByName['is_bot_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastMessagePreview =>
      columnsByName['last_message_preview']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastMessageAt =>
      columnsByName['last_message_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastInboundMessageAt =>
      columnsByName['last_inbound_message_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPinned =>
      columnsByName['is_pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isMuted =>
      columnsByName['is_muted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastEventAt =>
      columnsByName['last_event_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'channel_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'assignee_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_avatar_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'subject',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'unread_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_bot_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_bot_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tags',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_message_preview',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_message_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_inbound_message_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_pinned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_pinned IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_muted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_muted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_event_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get clientMessageId =>
      columnsByName['client_message_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get direction =>
      columnsByName['direction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mediaUrl =>
      columnsByName['media_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localMediaPath =>
      columnsByName['local_media_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorName =>
      columnsByName['author_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorId =>
      columnsByName['author_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isFromBot =>
      columnsByName['is_from_bot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get failureReason =>
      columnsByName['failure_reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get externalId =>
      columnsByName['external_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deliveredAt =>
      columnsByName['delivered_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get readAt =>
      columnsByName['read_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get queuedAt =>
      columnsByName['queued_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastEventAt =>
      columnsByName['last_event_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conversation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'client_message_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'direction',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'text\'',
      defaultValue: const i1.CustomExpression('\'text\''),
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'media_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_media_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'author_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'author_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_from_bot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_from_bot IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'failure_reason',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'external_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'delivered_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'read_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'queued_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['phone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get avatarUrl =>
      columnsByName['avatar_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPlatformAdmin =>
      columnsByName['is_platform_admin']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get permissions =>
      columnsByName['permissions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tenantId =>
      columnsByName['tenant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tenantName =>
      columnsByName['tenant_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'email',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locale',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'avatar_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_platform_admin',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (is_platform_admin IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'permissions',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tenant_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tenant_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get command =>
      columnsByName['command']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scopeId =>
      columnsByName['scope_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nextAttemptAt =>
      columnsByName['next_attempt_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'command',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scope_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'next_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pageCursor =>
      columnsByName['page_cursor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scope',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'synced_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'page_cursor',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'idle\'',
      defaultValue: const i1.CustomExpression('\'idle\''),
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get eventId =>
      columnsByName['event_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get eventName =>
      columnsByName['event_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get processedAt =>
      columnsByName['processed_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'processed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversations,
    messages,
    sessionUsers,
    outboxEntries,
    syncStates,
    processedEvents,
  ];
  late final Shape0 conversations = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messages = Shape1(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_1,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_17,
        _column_18,
        _column_32,
        _column_33,
        _column_34,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionUsers = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_61,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 outboxEntries = Shape3(
    source: i0.VersionedTable(
      entityName: 'outbox_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_17,
        _column_45,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 syncStates = Shape4(
    source: i0.VersionedTable(
      entityName: 'sync_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scope)'],
      columns: [
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 processedEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'processed_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(event_id)'],
      columns: [_column_58, _column_59, _column_60],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['phone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get avatarUrl =>
      columnsByName['avatar_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPlatformAdmin =>
      columnsByName['is_platform_admin']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get permissions =>
      columnsByName['permissions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get denied =>
      columnsByName['denied']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tenantId =>
      columnsByName['tenant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tenantName =>
      columnsByName['tenant_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'denied',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversations,
    messages,
    customers,
    customerNotes,
    sessionUsers,
    outboxEntries,
    syncStates,
    processedEvents,
  ];
  late final Shape0 conversations = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messages = Shape1(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_1,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_17,
        _column_18,
        _column_32,
        _column_33,
        _column_34,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 customers = Shape7(
    source: i0.VersionedTable(
      entityName: 'customers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_62,
        _column_37,
        _column_63,
        _column_64,
        _column_65,
        _column_10,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_17,
        _column_18,
        _column_71,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 customerNotes = Shape8(
    source: i0.VersionedTable(
      entityName: 'customer_notes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_72,
        _column_73,
        _column_28,
        _column_27,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionUsers = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_61,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 outboxEntries = Shape3(
    source: i0.VersionedTable(
      entityName: 'outbox_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_17,
        _column_45,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 syncStates = Shape4(
    source: i0.VersionedTable(
      entityName: 'sync_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scope)'],
      columns: [
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 processedEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'processed_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(event_id)'],
      columns: [_column_58, _column_59, _column_60],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phone =>
      columnsByName['phone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phoneDigits =>
      columnsByName['phone_digits']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phoneSuffix =>
      columnsByName['phone_suffix']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get typeId =>
      columnsByName['type_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get typeName =>
      columnsByName['type_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoUrl =>
      columnsByName['photo_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get seenAt =>
      columnsByName['seen_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'email',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone_digits',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone_suffix',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locale',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'ar\'',
      defaultValue: const i1.CustomExpression('\'ar\''),
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'photo_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'seen_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerId =>
      columnsByName['customer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorId =>
      columnsByName['author_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorName =>
      columnsByName['author_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'customer_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES customers(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversations,
    messages,
    customers,
    customerNotes,
    callerIdentityCaches,
    sessionUsers,
    outboxEntries,
    syncStates,
    processedEvents,
  ];
  late final Shape0 conversations = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messages = Shape1(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_1,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_17,
        _column_18,
        _column_32,
        _column_33,
        _column_34,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 customers = Shape7(
    source: i0.VersionedTable(
      entityName: 'customers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_62,
        _column_37,
        _column_63,
        _column_64,
        _column_65,
        _column_10,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_17,
        _column_18,
        _column_71,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 customerNotes = Shape8(
    source: i0.VersionedTable(
      entityName: 'customer_notes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_72,
        _column_73,
        _column_28,
        _column_27,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 callerIdentityCaches = Shape9(
    source: i0.VersionedTable(
      entityName: 'caller_identity_caches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(normalized_phone)'],
      columns: [
        _column_74,
        _column_75,
        _column_76,
        _column_40,
        _column_77,
        _column_78,
        _column_79,
        _column_3,
        _column_80,
        _column_81,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionUsers = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_61,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 outboxEntries = Shape3(
    source: i0.VersionedTable(
      entityName: 'outbox_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_17,
        _column_45,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 syncStates = Shape4(
    source: i0.VersionedTable(
      entityName: 'sync_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scope)'],
      columns: [
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 processedEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'processed_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(event_id)'],
      columns: [_column_58, _column_59, _column_60],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get normalizedPhone =>
      columnsByName['normalized_phone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get businessName =>
      columnsByName['business_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get avatarUrl =>
      columnsByName['avatar_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get spamStatus =>
      columnsByName['spam_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tagsJson =>
      columnsByName['tags_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerId =>
      columnsByName['customer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'normalized_phone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'business_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'spam_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'unknown\'',
      defaultValue: const i1.CustomExpression('\'unknown\''),
    );
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tags_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'unknown\'',
      defaultValue: const i1.CustomExpression('\'unknown\''),
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fetched_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'expires_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversations,
    messages,
    customers,
    customerNotes,
    callerIdentityCaches,
    sessionUsers,
    outboxEntries,
    syncStates,
    processedEvents,
  ];
  late final Shape10 conversations = Shape10(
    source: i0.VersionedTable(
      entityName: 'conversations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_82,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messages = Shape1(
    source: i0.VersionedTable(
      entityName: 'messages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_1,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_17,
        _column_18,
        _column_32,
        _column_33,
        _column_34,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 customers = Shape7(
    source: i0.VersionedTable(
      entityName: 'customers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_62,
        _column_37,
        _column_63,
        _column_64,
        _column_65,
        _column_10,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_17,
        _column_18,
        _column_71,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 customerNotes = Shape8(
    source: i0.VersionedTable(
      entityName: 'customer_notes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_72,
        _column_73,
        _column_28,
        _column_27,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 callerIdentityCaches = Shape9(
    source: i0.VersionedTable(
      entityName: 'caller_identity_caches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(normalized_phone)'],
      columns: [
        _column_74,
        _column_75,
        _column_76,
        _column_40,
        _column_77,
        _column_78,
        _column_79,
        _column_3,
        _column_80,
        _column_81,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionUsers = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_users',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_61,
        _column_43,
        _column_44,
        _column_45,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 outboxEntries = Shape3(
    source: i0.VersionedTable(
      entityName: 'outbox_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_17,
        _column_45,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 syncStates = Shape4(
    source: i0.VersionedTable(
      entityName: 'sync_states',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(scope)'],
      columns: [
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 processedEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'processed_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(event_id)'],
      columns: [_column_58, _column_59, _column_60],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get channelId =>
      columnsByName['channel_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerId =>
      columnsByName['customer_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assigneeId =>
      columnsByName['assignee_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerName =>
      columnsByName['customer_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customerAvatarUrl =>
      columnsByName['customer_avatar_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subject =>
      columnsByName['subject']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get unreadCount =>
      columnsByName['unread_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isBotEnabled =>
      columnsByName['is_bot_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get failedMessageCount =>
      columnsByName['failed_message_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastMessagePreview =>
      columnsByName['last_message_preview']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastMessageAt =>
      columnsByName['last_message_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastInboundMessageAt =>
      columnsByName['last_inbound_message_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isPinned =>
      columnsByName['is_pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isMuted =>
      columnsByName['is_muted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastEventAt =>
      columnsByName['last_event_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'failed_message_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
  ),
);
